server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /app/consumption_tracker/index.html;
    }

    location /app/consumption_tracker/ {
        try_files $uri $uri/ /app/consumption_tracker/index.html;
    }

    error_page 404 /app/consumption_tracker/index.html;
}
